###  Reshape

In [2]:
import numpy as np

In [3]:
ary2 = np.random.randint(100,150,(4,6))

In [4]:
ary2

array([[102, 110, 131, 100, 112, 137],
       [119, 130, 134, 132, 117, 111],
       [128, 121, 120, 107, 126, 111],
       [110, 127, 110, 142, 135, 146]])

In [5]:
ary2.shape

(4, 6)

In [6]:
ary2.size

24

In [9]:
ary3 = ary2.reshape(2,2,6)

In [10]:
ary2

array([[102, 110, 131, 100, 112, 137],
       [119, 130, 134, 132, 117, 111],
       [128, 121, 120, 107, 126, 111],
       [110, 127, 110, 142, 135, 146]])

In [11]:
ary3

array([[[102, 110, 131, 100, 112, 137],
        [119, 130, 134, 132, 117, 111]],

       [[128, 121, 120, 107, 126, 111],
        [110, 127, 110, 142, 135, 146]]])

In [14]:
ary2.shape

(4, 6)

In [15]:
ary3.shape

(2, 2, 6)

In [16]:
ary3.size

24

In [17]:
ary2.size

24

In [18]:
ary3.shape

(2, 2, 6)

In [20]:
ary4 = ary3.reshape(2,12)

In [21]:
ary4

array([[102, 110, 131, 100, 112, 137, 119, 130, 134, 132, 117, 111],
       [128, 121, 120, 107, 126, 111, 110, 127, 110, 142, 135, 146]])

In [22]:
ary3

array([[[102, 110, 131, 100, 112, 137],
        [119, 130, 134, 132, 117, 111]],

       [[128, 121, 120, 107, 126, 111],
        [110, 127, 110, 142, 135, 146]]])

In [23]:
ary3

array([[[102, 110, 131, 100, 112, 137],
        [119, 130, 134, 132, 117, 111]],

       [[128, 121, 120, 107, 126, 111],
        [110, 127, 110, 142, 135, 146]]])

In [24]:
ary3.size

24

In [25]:
ary3.reshape(4,8)

ValueError: cannot reshape array of size 24 into shape (4,8)

###  Resize

In [26]:
ary2

array([[102, 110, 131, 100, 112, 137],
       [119, 130, 134, 132, 117, 111],
       [128, 121, 120, 107, 126, 111],
       [110, 127, 110, 142, 135, 146]])

In [27]:
ary2.shape

(4, 6)

In [28]:
ary2.resize(12,2)

In [29]:
ary2.shape

(12, 2)

In [30]:
ary2

array([[102, 110],
       [131, 100],
       [112, 137],
       [119, 130],
       [134, 132],
       [117, 111],
       [128, 121],
       [120, 107],
       [126, 111],
       [110, 127],
       [110, 142],
       [135, 146]])

In [32]:
ary2.shape

(12, 2)

In [31]:
ary2.size

24

In [34]:
ary2.resize((4,8),refcheck = False)

In [35]:
ary2

array([[102, 110, 131, 100, 112, 137, 119, 130],
       [134, 132, 117, 111, 128, 121, 120, 107],
       [126, 111, 110, 127, 110, 142, 135, 146],
       [  0,   0,   0,   0,   0,   0,   0,   0]])

In [36]:
ary3

array([[[50, 48, 50, 51, 45, 48],
        [51, 45, 50, 52, 84, 48]],

       [[52, 58, 53, 50, 58, 49],
        [49, 46, 56, 49, 53, 90]]])

In [37]:
ary3.shape

(2, 2, 6)

In [38]:
ary3.resize(4,6)

In [39]:
ary3

array([[-2135210552,         567,          50,           0,           0,
                  0],
       [          0,           0,           0,          52,  1852990827,
          875457637],
       [  809001315,   758331185,   943285091,   808662061,   828452144,
          908932409],
       [  825373537,   892822625,   778122295,  1952543859,       29557,
                 90]])

In [40]:
ary4

array([[-2135210552,         567,          64,           0,           0,
                  0,           0,           0,           0,          52,
         1717908017,  1701012278],
       [ 1667445557,   828728113,   943143266,   842020659,  1684420917,
         1667446072,   808596067,  1664430129,  1681285688,   912417332,
          808923233,  1717975137]])

In [41]:
ary3 = np.random.randint(100,200,(4,6))

In [42]:
ary3

array([[126, 176, 100, 190, 143, 173],
       [160, 187, 107, 190, 152, 145],
       [187, 197, 136, 198, 165, 195],
       [118, 169, 145, 101, 145, 180]])

In [45]:
np.resize(ary3,(6,6) )

array([[126, 176, 100, 190, 143, 173],
       [160, 187, 107, 190, 152, 145],
       [187, 197, 136, 198, 165, 195],
       [118, 169, 145, 101, 145, 180],
       [126, 176, 100, 190, 143, 173],
       [160, 187, 107, 190, 152, 145]])

### Transpose

In [47]:
ary2 = np.random.randint(100,200,(4,7))

In [48]:
ary2

array([[108, 108, 131, 161, 155, 188, 100],
       [123, 120, 134, 147, 112, 186, 128],
       [197, 138, 115, 153, 187, 131, 151],
       [156, 123, 136, 162, 182, 145, 101]])

In [49]:
ary2.shape

(4, 7)

In [50]:
ary2.transpose()

array([[108, 123, 197, 156],
       [108, 120, 138, 123],
       [131, 134, 115, 136],
       [161, 147, 153, 162],
       [155, 112, 187, 182],
       [188, 186, 131, 145],
       [100, 128, 151, 101]])

In [51]:
ary2.transpose().shape

(7, 4)

In [52]:
ary2.T

array([[108, 123, 197, 156],
       [108, 120, 138, 123],
       [131, 134, 115, 136],
       [161, 147, 153, 162],
       [155, 112, 187, 182],
       [188, 186, 131, 145],
       [100, 128, 151, 101]])

In [53]:
a3 = np.random.randint(100,200,(2,4,6))

In [54]:
a3

array([[[104, 164, 164, 117, 162, 184],
        [118, 192, 132, 139, 100, 190],
        [103, 171, 152, 149, 162, 184],
        [168, 177, 173, 122, 118, 168]],

       [[184, 190, 127, 137, 183, 179],
        [111, 180, 191, 163, 100, 176],
        [121, 195, 121, 169, 143, 138],
        [142, 128, 125, 169, 197, 157]]])

In [55]:
a3.shape

(2, 4, 6)

In [58]:
at = a3.transpose()

In [59]:
at

array([[[104, 184],
        [118, 111],
        [103, 121],
        [168, 142]],

       [[164, 190],
        [192, 180],
        [171, 195],
        [177, 128]],

       [[164, 127],
        [132, 191],
        [152, 121],
        [173, 125]],

       [[117, 137],
        [139, 163],
        [149, 169],
        [122, 169]],

       [[162, 183],
        [100, 100],
        [162, 143],
        [118, 197]],

       [[184, 179],
        [190, 176],
        [184, 138],
        [168, 157]]])

In [60]:
at.shape

(6, 4, 2)

In [63]:
a3.shape

(2, 4, 6)

In [64]:
# 4, 6,2

In [65]:
a3

array([[[104, 164, 164, 117, 162, 184],
        [118, 192, 132, 139, 100, 190],
        [103, 171, 152, 149, 162, 184],
        [168, 177, 173, 122, 118, 168]],

       [[184, 190, 127, 137, 183, 179],
        [111, 180, 191, 163, 100, 176],
        [121, 195, 121, 169, 143, 138],
        [142, 128, 125, 169, 197, 157]]])

In [66]:
a3.shape

(2, 4, 6)

In [68]:
a4 = a3.transpose(1,2,0)

In [69]:
a3.shape

(2, 4, 6)

In [70]:
a4.shape

(4, 6, 2)

In [72]:
ary4 = np.random.randint(100,200,(2,4,6,8))

In [73]:
ary4

array([[[[188, 126, 101, 193, 178, 177, 108, 153],
         [141, 154, 138, 134, 138, 166, 134, 144],
         [151, 197, 111, 123, 196, 195, 165, 116],
         [140, 178, 118, 127, 131, 180, 158, 153],
         [163, 147, 100, 194, 197, 147, 175, 161],
         [180, 197, 162, 173, 109, 146, 106, 152]],

        [[170, 181, 186, 184, 194, 191, 121, 122],
         [153, 155, 185, 176, 193, 151, 184, 199],
         [160, 193, 126, 179, 184, 199, 168, 181],
         [112, 121, 122, 133, 154, 199, 162, 176],
         [154, 128, 100, 196, 100, 135, 117, 108],
         [182, 122, 129, 164, 181, 158, 178, 109]],

        [[111, 151, 182, 127, 154, 149, 151, 146],
         [122, 151, 106, 195, 103, 145, 195, 155],
         [174, 178, 122, 158, 162, 167, 189, 101],
         [142, 115, 179, 164, 137, 173, 146, 119],
         [103, 179, 162, 128, 142, 127, 135, 102],
         [128, 169, 134, 159, 144, 136, 122, 119]],

        [[115, 154, 160, 162, 119, 109, 142, 135],
         [146, 191, 144, 

In [75]:
ary5 = ary4.transpose()

In [76]:
ary4.shape

(2, 4, 6, 8)

In [77]:
ary5.shape

(8, 6, 4, 2)

In [78]:
# 4, 8, 2, 6

ary6 = ary4.transpose(1,3,0,2)

In [79]:
ary4.shape

(2, 4, 6, 8)

In [80]:
ary6.shape

(4, 8, 2, 6)

In [81]:
ary3

array([[126, 176, 100, 190, 143, 173],
       [160, 187, 107, 190, 152, 145],
       [187, 197, 136, 198, 165, 195],
       [118, 169, 145, 101, 145, 180]])

In [83]:
a3.shape

(2, 4, 6)

###  Swapaxes

In [84]:
a3.swapaxes(1,0)

array([[[104, 164, 164, 117, 162, 184],
        [184, 190, 127, 137, 183, 179]],

       [[118, 192, 132, 139, 100, 190],
        [111, 180, 191, 163, 100, 176]],

       [[103, 171, 152, 149, 162, 184],
        [121, 195, 121, 169, 143, 138]],

       [[168, 177, 173, 122, 118, 168],
        [142, 128, 125, 169, 197, 157]]])

In [85]:
a3.swapaxes(1,0).shape

(4, 2, 6)

### Flatten

In [86]:
ary3

array([[126, 176, 100, 190, 143, 173],
       [160, 187, 107, 190, 152, 145],
       [187, 197, 136, 198, 165, 195],
       [118, 169, 145, 101, 145, 180]])

In [87]:
ary3.flatten()

array([126, 176, 100, 190, 143, 173, 160, 187, 107, 190, 152, 145, 187,
       197, 136, 198, 165, 195, 118, 169, 145, 101, 145, 180])

In [88]:
ary3.flatten(order = "F")

array([126, 160, 187, 118, 176, 187, 197, 169, 100, 107, 136, 145, 190,
       190, 198, 101, 143, 152, 165, 145, 173, 145, 195, 180])

In [89]:
ary3

array([[126, 176, 100, 190, 143, 173],
       [160, 187, 107, 190, 152, 145],
       [187, 197, 136, 198, 165, 195],
       [118, 169, 145, 101, 145, 180]])

### Ravel

In [90]:
np.ravel(ary3,order="C")

array([126, 176, 100, 190, 143, 173, 160, 187, 107, 190, 152, 145, 187,
       197, 136, 198, 165, 195, 118, 169, 145, 101, 145, 180])

In [91]:
np.ravel(ary3,order="F")

array([126, 160, 187, 118, 176, 187, 197, 169, 100, 107, 136, 145, 190,
       190, 198, 101, 143, 152, 165, 145, 173, 145, 195, 180])

In [94]:
a = np.random.randint(10,20,(8))

In [95]:
a

array([18, 16, 10, 15, 16, 11, 10, 11])

In [96]:
a.dtype

dtype('int32')

In [101]:
a = np.array( [18, 16, 10, 15, "Nan", 11, 10, 11] )

In [102]:
a

array(['18', '16', '10', '15', 'Nan', '11', '10', '11'], dtype='<U11')

In [103]:
type(a)

numpy.ndarray

In [104]:
a.mean()

TypeError: cannot perform reduce with flexible type

In [105]:
b  = np.array([10,20,30,40,50])

In [106]:
b

array([10, 20, 30, 40, 50])

In [107]:
b.mean()

30.0

In [109]:
b  = np.array([10,20,np.nan,40,50])

In [110]:
b

array([10., 20., nan, 40., 50.])

In [111]:
b.mean()

nan

In [112]:
import pandas as pd

In [114]:
d1 = pd.DataFrame(b)

In [116]:
d1

0
0  10.0
1  20.0
2   NaN
3  40.0
4  50.0

In [115]:
d1.mean()

0    30.0
dtype: float64

In [117]:
d1.fillna(d1.mean())

0
0  10.0
1  20.0
2  30.0
3  40.0
4  50.0

###  np.where

In [124]:
# np.where(<condition>, <True Output>, <False output> )

np.where(100> 500, 100, 500)

array(500)

In [130]:
a = 1100
b = 2000
c = 300

In [131]:
np.where( a > b and a > c, a, np.where(b>c, b, c))

array(2000)

In [132]:
x = np.random.randint(10,30,(5))

In [133]:
y = np.random.randint(10,30,(5))

In [134]:
x

array([27, 25, 18, 12, 25])

In [135]:
y

array([11, 18, 10, 26, 24])

In [136]:
np.where(x > y, x, y)

array([27, 25, 18, 26, 25])