In [1]:
import numpy as np

### Creating Numpy Array using Random.

In [3]:
rand_ary1 = np.random.rand(3,5)

In [4]:
rand_ary1

array([[0.90081181, 0.5639247 , 0.55875737, 0.67152972, 0.84607822],
       [0.12543572, 0.86111451, 0.93531629, 0.62416556, 0.34086454],
       [0.79378887, 0.27679692, 0.9617748 , 0.53480086, 0.49332985]])

In [9]:
rand_ary3 = np.random.rand(2,4,5)

In [10]:
rand_ary3

array([[[0.38525761, 0.35071849, 0.58988331, 0.16097518, 0.74124573],
        [0.76460677, 0.84928926, 0.52192836, 0.96558862, 0.14148215],
        [0.06594807, 0.92598169, 0.89225868, 0.97989593, 0.06260202],
        [0.10071211, 0.25797397, 0.16326503, 0.16145806, 0.89272791]],

       [[0.8953493 , 0.7999063 , 0.03870475, 0.86745512, 0.07659404],
        [0.02788231, 0.55191752, 0.04743589, 0.77654562, 0.22592239],
        [0.88101027, 0.34134314, 0.41876574, 0.78683567, 0.798217  ],
        [0.56105497, 0.0383251 , 0.56564328, 0.78438073, 0.46690278]]])

###  Random.Randn

In [11]:
randn_ary1 = np.random.randn(4,5)

In [12]:
randn_ary1

array([[-0.12959981,  0.78003289,  0.00522318, -1.16914479,  0.03162725],
       [-0.99220103,  0.30048168,  2.26437334, -0.40737924, -0.1070578 ],
       [-2.11265876, -1.7882754 ,  0.70729048, -0.20763619, -1.49396894],
       [ 1.06658646, -0.4382533 , -0.13592841, -0.59436272,  0.91315899]])

In [13]:
randn_ary2 = np.random.randn(2,4,5)

In [14]:
randn_ary2

array([[[-0.72898536,  0.67818973, -1.18772645, -0.21246638,
         -1.24673185],
        [ 0.30830202, -0.53550911,  0.20394499,  0.21442291,
         -1.7443416 ],
        [ 0.88000196,  2.08637033, -0.25499683, -1.18908435,
          1.44386535],
        [ 1.59082108,  0.47993271,  0.11654107,  1.25838134,
         -1.77348935]],

       [[ 1.98085787,  1.470055  ,  0.77108438, -0.83450356,
          1.24640762],
        [-1.67735869,  1.18037127,  1.07325296,  0.95302051,
         -0.08634007],
        [ 0.56522019,  0.27928805, -1.45859132, -1.14857048,
          0.7170283 ],
        [ 0.34213893, -0.22384124,  1.9122933 ,  0.08292016,
         -0.91408646]]])

### Random.randint

In [16]:
int_ary1 = np.random.randint(5, 15,(4,6))

In [17]:
int_ary1

array([[ 5, 13, 13,  5,  5, 14],
       [12, 13, 14, 12,  8, 13],
       [ 6, 11, 13, 10, 10,  5],
       [13, 13,  5,  9, 10, 13]])

In [18]:
int_ary1.shape

(4, 6)

In [19]:
int_ary1.ndim

2

In [20]:
int_ary1.size

24

In [21]:
int_ary1.dtype

dtype('int32')

In [28]:
int_ary2 = np.random.randint(5,10,(3,5))

In [29]:
int_ary2

array([[8, 8, 6, 5, 8],
       [9, 5, 5, 5, 9],
       [5, 7, 5, 8, 7]])

In [32]:
nary1 = np.arange(5,9)

In [31]:
np.random.randint(5,9,(4,6))

array([[8, 8, 7, 5, 8, 5],
       [8, 7, 5, 8, 6, 8],
       [7, 6, 8, 8, 7, 5],
       [7, 5, 8, 6, 5, 8]])

In [33]:
nary1

array([5, 6, 7, 8])

In [36]:
np.random.choice(nary1,(3,4),p = [0.1, 0.2 , 0.0 ,0.7  ])

array([[8, 8, 8, 6],
       [8, 8, 8, 6],
       [8, 8, 5, 8]])

###  Indexing & Slicing

In [37]:
rary1 = np.random.randint(2,6,(5,))

In [38]:
rary1

array([2, 2, 3, 4, 5])

In [39]:
rary1[3]

4

In [40]:
rary1[-2]

4

In [41]:
ary2 = np.random.randint(10,20,(3,5))

In [42]:
ary2

array([[16, 15, 10, 16, 11],
       [18, 13, 16, 11, 17],
       [18, 15, 14, 13, 19]])

In [43]:
# row index = 1
# col index = 2

ary2[1][2]

16

In [44]:
ary2.ndim

2

In [45]:
# ary2[ <Rows>  , <Columns>  ]

ary2[1, 2]

16

In [46]:
rary2 = np.random.randint(100,200,(5,9))

In [47]:
rary2

array([[189, 136, 158, 192, 127, 113, 154, 116, 194],
       [185, 193, 130, 107, 108, 110, 136, 198, 164],
       [181, 140, 137, 107, 125, 139, 107, 157, 109],
       [193, 156, 196, 161, 178, 120, 106, 143, 164],
       [131, 145, 171, 109, 146, 196, 111, 125, 113]])

In [48]:
rary2[2,6]

107

In [49]:
rary2[1, 4]

108

###  Indexing with Multi Dimension Array

In [50]:
rary3 = np.random.randint(100,200,(2,4,6))

In [51]:
rary3

array([[[181, 188, 110, 113, 197, 165],
        [134, 121, 166, 183, 137, 105],
        [140, 155, 114, 170, 174, 149],
        [117, 175, 135, 183, 175, 157]],

       [[156, 191, 109, 189, 175, 184],
        [117, 134, 136, 160, 161, 152],
        [171, 160, 137, 137, 112, 131],
        [187, 121, 133, 165, 101, 134]]])

In [52]:
rary3.ndim

3

In [53]:
rary3.shape

(2, 4, 6)

In [54]:
rary4 = np.random.randint(100,200,(2,3,4,5))

In [55]:
rary4

array([[[[185, 151, 163, 140, 140],
         [132, 113, 169, 145, 144],
         [100, 144, 194, 100, 133],
         [122, 160, 100, 105, 165]],

        [[116, 101, 172, 178, 173],
         [163, 116, 177, 193, 118],
         [150, 174, 115, 113, 166],
         [189, 110, 195, 133, 105]],

        [[130, 104, 146, 132, 175],
         [102, 114, 133, 138, 123],
         [154, 136, 199, 158, 129],
         [104, 161, 130, 162, 115]]],


       [[[127, 167, 183, 143, 170],
         [157, 128, 108, 193, 194],
         [182, 153, 110, 149, 197],
         [189, 176, 144, 134, 178]],

        [[161, 154, 140, 116, 165],
         [104, 150, 137, 103, 161],
         [159, 186, 132, 182, 120],
         [111, 170, 189, 185, 172]],

        [[118, 171, 123, 178, 172],
         [150, 146, 138, 192, 173],
         [162, 198, 173, 111, 187],
         [129, 116, 142, 190, 149]]]])

In [57]:
rary4[0,1,2,2]

115

In [59]:
import time

In [62]:
for i in rary4:
    time.sleep(2)
    for j in i :
        print(j)
        time.sleep(2)

[[[185 151 163 140 140]
  [132 113 169 145 144]
  [100 144 194 100 133]
  [122 160 100 105 165]]

 [[116 101 172 178 173]
  [163 116 177 193 118]
  [150 174 115 113 166]
  [189 110 195 133 105]]

 [[130 104 146 132 175]
  [102 114 133 138 123]
  [154 136 199 158 129]
  [104 161 130 162 115]]]
[[185 151 163 140 140]
 [132 113 169 145 144]
 [100 144 194 100 133]
 [122 160 100 105 165]]
[[116 101 172 178 173]
 [163 116 177 193 118]
 [150 174 115 113 166]
 [189 110 195 133 105]]
[[130 104 146 132 175]
 [102 114 133 138 123]
 [154 136 199 158 129]
 [104 161 130 162 115]]
[[[127 167 183 143 170]
  [157 128 108 193 194]
  [182 153 110 149 197]
  [189 176 144 134 178]]

 [[161 154 140 116 165]
  [104 150 137 103 161]
  [159 186 132 182 120]
  [111 170 189 185 172]]

 [[118 171 123 178 172]
  [150 146 138 192 173]
  [162 198 173 111 187]
  [129 116 142 190 149]]]
[[127 167 183 143 170]
 [157 128 108 193 194]
 [182 153 110 149 197]
 [189 176 144 134 178]]
[[161 154 140 116 165]
 [104 150 137 103

###  Slicing

In [64]:
rary1 = np.random.randint(1,10,(8))

In [65]:
rary1

array([5, 2, 3, 8, 1, 1, 5, 1])

In [66]:
rary1[2 : 6 : 1]

array([3, 8, 1, 1])

In [67]:
rary1[1 : 7 : 1]

array([2, 3, 8, 1, 1, 5])

###  Two DImension Array Slicing

In [68]:
rary2

array([[189, 136, 158, 192, 127, 113, 154, 116, 194],
       [185, 193, 130, 107, 108, 110, 136, 198, 164],
       [181, 140, 137, 107, 125, 139, 107, 157, 109],
       [193, 156, 196, 161, 178, 120, 106, 143, 164],
       [131, 145, 171, 109, 146, 196, 111, 125, 113]])

In [69]:
rary2.ndim

2

In [70]:
 rary2 [    1: 4 : 1    ,     2: 7: 1   ]


array([[130, 107, 108, 110, 136],
       [137, 107, 125, 139, 107],
       [196, 161, 178, 120, 106]])

In [71]:
 rary2[  0 : 5 : 1        ,  1 : 7 : 1       ]

array([[136, 158, 192, 127, 113, 154],
       [193, 130, 107, 108, 110, 136],
       [140, 137, 107, 125, 139, 107],
       [156, 196, 161, 178, 120, 106],
       [145, 171, 109, 146, 196, 111]])

In [72]:
rary2[  :  :     ,  1 : 7 : 1       ]

array([[136, 158, 192, 127, 113, 154],
       [193, 130, 107, 108, 110, 136],
       [140, 137, 107, 125, 139, 107],
       [156, 196, 161, 178, 120, 106],
       [145, 171, 109, 146, 196, 111]])

In [73]:
 rary2[  1 : 4 : 1, 1 : 8: 2 ]


array([[193, 107, 110, 198],
       [140, 107, 139, 157],
       [156, 161, 120, 143]])

In [74]:
rary3

array([[[181, 188, 110, 113, 197, 165],
        [134, 121, 166, 183, 137, 105],
        [140, 155, 114, 170, 174, 149],
        [117, 175, 135, 183, 175, 157]],

       [[156, 191, 109, 189, 175, 184],
        [117, 134, 136, 160, 161, 152],
        [171, 160, 137, 137, 112, 131],
        [187, 121, 133, 165, 101, 134]]])

In [75]:
 rary3[   0 : 2 : 1  ,  1 : 4 : 2   ,   1 : 5 : 1 ]


array([[[121, 166, 183, 137],
        [175, 135, 183, 175]],

       [[134, 136, 160, 161],
        [121, 133, 165, 101]]])

In [78]:
ary3 = np.random.randint(100,300,(3,5,8))

In [79]:
ary3

array([[[220, 270, 255, 166, 234, 156, 143, 252],
        [162, 187, 166, 193, 247, 230, 181, 135],
        [113, 200, 222, 167, 168, 171, 279, 131],
        [227, 243, 154, 172, 201, 259, 139, 247],
        [171, 135, 299, 139, 295, 107, 251, 194]],

       [[201, 185, 131, 112, 222, 267, 227, 254],
        [145, 109, 241, 282, 168, 115, 167, 126],
        [164, 246, 243, 222, 174, 283, 187, 112],
        [166, 212, 194, 220, 130, 136, 111, 185],
        [209, 221, 121, 283, 268, 255, 206, 290]],

       [[121, 280, 148, 264, 164, 255, 278, 154],
        [168, 108, 272, 145, 251, 252, 204, 106],
        [288, 177, 158, 136, 172, 255, 171, 147],
        [233, 280, 162, 170, 113, 151, 108, 260],
        [281, 114, 199, 152, 275, 117, 246, 277]]])

### Advance Indexing

In [81]:
rary1

array([5, 2, 3, 8, 1, 1, 5, 1])

In [82]:
# 2, 8, 5,1

rary1[ [1,3,6,7] ]

array([2, 8, 5, 1])

In [83]:
rary2

array([[189, 136, 158, 192, 127, 113, 154, 116, 194],
       [185, 193, 130, 107, 108, 110, 136, 198, 164],
       [181, 140, 137, 107, 125, 139, 107, 157, 109],
       [193, 156, 196, 161, 178, 120, 106, 143, 164],
       [131, 145, 171, 109, 146, 196, 111, 125, 113]])

In [84]:
 rary2 [   [2, 1, 4, 0, 3, 4, 1 ]   ,    [1,  3, 4 , 6, 7, 8, 0]  ]

array([140, 107, 146, 154, 143, 113, 185])

In [86]:
ary3

array([[[220, 270, 255, 166, 234, 156, 143, 252],
        [162, 187, 166, 193, 247, 230, 181, 135],
        [113, 200, 222, 167, 168, 171, 279, 131],
        [227, 243, 154, 172, 201, 259, 139, 247],
        [171, 135, 299, 139, 295, 107, 251, 194]],

       [[201, 185, 131, 112, 222, 267, 227, 254],
        [145, 109, 241, 282, 168, 115, 167, 126],
        [164, 246, 243, 222, 174, 283, 187, 112],
        [166, 212, 194, 220, 130, 136, 111, 185],
        [209, 221, 121, 283, 268, 255, 206, 290]],

       [[121, 280, 148, 264, 164, 255, 278, 154],
        [168, 108, 272, 145, 251, 252, 204, 106],
        [288, 177, 158, 136, 172, 255, 171, 147],
        [233, 280, 162, 170, 113, 151, 108, 260],
        [281, 114, 199, 152, 275, 117, 246, 277]]])

In [87]:
 ary3[  [0, 2, 1, 1] ,  [2, 1, 0,4]  ,  [2, 0,6, 0] ]

array([222, 168, 227, 209])

In [88]:
bary2 = np.random.randint(50, 350,(5,10))

In [89]:
bary2

array([[ 82, 287, 331, 202, 296, 228,  78, 167, 343, 115],
       [ 68, 218, 179, 331, 135, 320, 304, 283, 231, 250],
       [133, 224, 189, 125, 204, 338, 276, 113, 169,  83],
       [274,  62, 100,  62,  88, 269, 303,  81, 209, 208],
       [239, 337,  94, 160, 176, 147, 191, 236,  54,  55]])

In [90]:
bary2 < 100

array([[ True, False, False, False, False, False,  True, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False,  True, False,  True,  True, False, False,  True, False,
        False],
       [False, False,  True, False, False, False, False, False,  True,
         True]])

In [92]:
bary2[  bary2 < 100 ]

array([82, 78, 68, 83, 62, 62, 88, 81, 94, 54, 55])

In [94]:
filt = bary2 > 200

In [95]:
filt

array([[False,  True,  True,  True,  True,  True, False, False,  True,
        False],
       [False,  True, False,  True, False,  True,  True,  True,  True,
         True],
       [False,  True, False, False,  True,  True,  True, False, False,
        False],
       [ True, False, False, False, False,  True,  True, False,  True,
         True],
       [ True,  True, False, False, False, False, False,  True, False,
        False]])

In [96]:
bary2[  filt ]

array([287, 331, 202, 296, 228, 343, 218, 331, 320, 304, 283, 231, 250,
       224, 204, 338, 276, 274, 269, 303, 209, 208, 239, 337, 236])

In [97]:
bary2

array([[ 82, 287, 331, 202, 296, 228,  78, 167, 343, 115],
       [ 68, 218, 179, 331, 135, 320, 304, 283, 231, 250],
       [133, 224, 189, 125, 204, 338, 276, 113, 169,  83],
       [274,  62, 100,  62,  88, 269, 303,  81, 209, 208],
       [239, 337,  94, 160, 176, 147, 191, 236,  54,  55]])

In [100]:
filt1 = (bary2 > 100)   &   (bary2 < 200)

In [101]:
filt1

array([[False, False, False, False, False, False, False,  True, False,
         True],
       [False, False,  True, False,  True, False, False, False, False,
        False],
       [ True, False,  True,  True, False, False, False,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True,  True,  True, False, False,
        False]])

In [102]:
bary2[ filt1  ]

array([167, 115, 179, 135, 133, 189, 125, 113, 169, 160, 176, 147, 191])

In [103]:
bary2

array([[ 82, 287, 331, 202, 296, 228,  78, 167, 343, 115],
       [ 68, 218, 179, 331, 135, 320, 304, 283, 231, 250],
       [133, 224, 189, 125, 204, 338, 276, 113, 169,  83],
       [274,  62, 100,  62,  88, 269, 303,  81, 209, 208],
       [239, 337,  94, 160, 176, 147, 191, 236,  54,  55]])

In [105]:
(bary2 < 100) |  (bary2 > 200)

array([[ True,  True,  True,  True,  True,  True,  True, False,  True,
        False],
       [ True,  True, False,  True, False,  True,  True,  True,  True,
         True],
       [False,  True, False, False,  True,  True,  True, False, False,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True]])

In [106]:
bary2[      (bary2 < 100) |  (bary2 > 200)           ]

array([ 82, 287, 331, 202, 296, 228,  78, 343,  68, 218, 331, 320, 304,
       283, 231, 250, 224, 204, 338, 276,  83, 274,  62,  62,  88, 269,
       303,  81, 209, 208, 239, 337,  94, 236,  54,  55])

###  Numpy array occupies less memory

In [108]:
rary1

array([5, 2, 3, 8, 1, 1, 5, 1])

In [110]:
len(rary1)

8

In [111]:
rary1.size

8

In [112]:
rary1.itemsize

4

In [113]:
rary1.dtype

dtype('int32')

In [114]:
rary1.itemsize * rary1.size

32

In [115]:
nlist = [5, 2, 3, 8, 1, 1, 5, 1]

In [116]:
nlist

[5, 2, 3, 8, 1, 1, 5, 1]

In [117]:
type(nlist)

list

In [118]:
import sys

In [119]:
sys.getsizeof(8)

28

In [120]:
sys.getsizeof(nlist[3])

28

In [122]:
len(nlist) * sys.getsizeof(nlist[3])

224

### Speed check of Numpy over List

In [123]:
nmax = 100000

In [125]:
list( range(10) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [127]:
num1 = list(range(nmax))

In [128]:
num2 = list(range(nmax))

In [129]:
len(num1)

100000

In [130]:
len(num2)

100000

In [131]:
type(num1)

list

In [132]:
type(num2)

list

In [133]:
n1 = [10,20,30,40,50]
n2 = [1,2,3,4,5]

In [134]:
n1 + n2

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]

In [136]:
n3 = []
for i, j in zip(n1, n2):
    print(i)
    print(j)
    n3.append(i+j)
    print()

10
1

20
2

30
3

40
4

50
5



In [137]:
n3

[11, 22, 33, 44, 55]

In [138]:
st = time.time()
num3 = []
for x, y in zip(num1, num2) : 
    num3.append(x+y)
    
et = time.time()

print((et - st) * 1000)

18.022775650024414


In [139]:
nary1 = np.arange(nmax)
nary2 = np.arange(nmax)

In [140]:
nary1

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [141]:
nary2

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [142]:
nary3 = nary1 + nary2

In [143]:
nary3

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [144]:
nst = time.time()

nary4 = nary1 + nary2

net = time.time()  

print(( net - nst) * 1000 ) 

1.0004043579101562
