### Operations

In [1]:
import numpy as np

In [3]:
a1  = np.random.randint(10,20,(5,))

In [5]:
b1  = np.random.randint(1,10,(5,))

In [6]:
a1

array([10, 18, 17, 12, 11])

In [9]:
a1.size

5

In [7]:
b1

array([1, 4, 1, 3, 3])

In [10]:
b1.size

5

In [8]:
a1 + b1

array([11, 22, 18, 15, 14])

In [11]:
x1 = np.random.randint(10,20,(8))

In [12]:
x1

array([13, 14, 12, 10, 11, 17, 10, 13])

In [13]:
x1.size

8

In [14]:
a1 + x1

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [15]:
a1

array([10, 18, 17, 12, 11])

In [16]:
a1 + 6

array([16, 24, 23, 18, 17])

In [17]:
a1

array([10, 18, 17, 12, 11])

In [18]:
b1

array([1, 4, 1, 3, 3])

In [19]:
a1 + b1

array([11, 22, 18, 15, 14])

In [20]:
np.add(a1, b1)

array([11, 22, 18, 15, 14])

In [21]:
a1

array([10, 18, 17, 12, 11])

In [22]:
b1

array([1, 4, 1, 3, 3])

In [23]:
a1-b1

array([ 9, 14, 16,  9,  8])

In [24]:
np.subtract(a1, b1)

array([ 9, 14, 16,  9,  8])

In [26]:
a1

array([10, 18, 17, 12, 11])

In [27]:
b1

array([1, 4, 1, 3, 3])

In [25]:
a1 * b1

array([10, 72, 17, 36, 33])

In [28]:
np.multiply(a1, b1)

array([10, 72, 17, 36, 33])

In [29]:
a1

array([10, 18, 17, 12, 11])

In [30]:
b1

array([1, 4, 1, 3, 3])

In [31]:
a1/b1

array([10.        ,  4.5       , 17.        ,  4.        ,  3.66666667])

In [32]:
np.divide(a1,b1)

array([10.        ,  4.5       , 17.        ,  4.        ,  3.66666667])

##  Two Dimension Array

In [36]:
a2 = np.random.randint(1,6,(2,2))

In [46]:
b2 = np.random.randint(4,11,(2,2))

In [47]:
a2

array([[5, 3],
       [4, 4]])

In [48]:
b2

array([[ 9,  8],
       [10,  6]])

In [49]:
a2.shape

(2, 2)

In [50]:
b2.shape

(2, 2)

In [51]:
a2 + b2

array([[14, 11],
       [14, 10]])

In [52]:
a2*b2

array([[45, 24],
       [40, 24]])

In [53]:
np.multiply(a2, b2)

array([[45, 24],
       [40, 24]])

In [54]:
a2

array([[5, 3],
       [4, 4]])

In [55]:
b2

array([[ 9,  8],
       [10,  6]])

In [56]:
a2 - b2

array([[-4, -5],
       [-6, -2]])

### Two Dimension with different Shape

In [57]:
x2 = np.random.randint(1,10,(3,3))

In [58]:
x2

array([[8, 1, 4],
       [6, 7, 8],
       [7, 2, 4]])

In [59]:
x2.shape

(3, 3)

In [60]:
x2.ndim

2

In [61]:
a2

array([[5, 3],
       [4, 4]])

In [62]:
a2.shape

(2, 2)

In [64]:
a2.ndim

2

In [65]:
a2 + x2

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

###   Shape -->  Same 
###  Dimension --> Same

In [66]:
a1

array([10, 18, 17, 12, 11])

In [67]:
b1

array([1, 4, 1, 3, 3])

In [68]:
a1.shape

(5,)

In [69]:
b1.shape

(5,)

In [70]:
a1.ndim

1

In [71]:
b1.ndim

1

In [72]:
a1 + b1 

array([11, 22, 18, 15, 14])

In [73]:
a1 - b1

array([ 9, 14, 16,  9,  8])

In [74]:
a1 * b1

array([10, 72, 17, 36, 33])

In [75]:
a1/b1

array([10.        ,  4.5       , 17.        ,  4.        ,  3.66666667])

In [76]:
a2

array([[5, 3],
       [4, 4]])

In [77]:
b2

array([[ 9,  8],
       [10,  6]])

In [78]:
print("Shape : ",a2.shape)
print("Dimension : ",a2.ndim)

Shape :  (2, 2)
Dimension :  2


In [79]:
print("Shape : ",b2.shape)
print("Dimension : ",b2.ndim)

Shape :  (2, 2)
Dimension :  2


In [80]:
a2 + b2

array([[14, 11],
       [14, 10]])

In [81]:
a2 - b2

array([[-4, -5],
       [-6, -2]])

In [82]:
a2 * b2

array([[45, 24],
       [40, 24]])

In [83]:
a2 / b2

array([[0.55555556, 0.375     ],
       [0.4       , 0.66666667]])

In [84]:
a2.dot(b2)

array([[75, 58],
       [76, 56]])

In [85]:
a2 * b2

array([[45, 24],
       [40, 24]])

In [86]:
a2

array([[5, 3],
       [4, 4]])

In [87]:
b2

array([[ 9,  8],
       [10,  6]])

In [88]:
a3  = np.random.randint(1,20, (3,3))

In [89]:
b3 = np.random.randint(1,20,(3,3))

In [90]:
print(a3)
print("Shape : ",a3.shape)
print("Dimension : ",a3.ndim)

[[18 16 16]
 [ 7 16  5]
 [ 7 12 18]]
Shape :  (3, 3)
Dimension :  2


In [91]:
print(b3)
print("Shape : ",b3.shape)
print("Dimension : ",b3.ndim)

[[17  9 17]
 [ 5 10  7]
 [12 15 12]]
Shape :  (3, 3)
Dimension :  2


In [92]:
a3 + b3

array([[35, 25, 33],
       [12, 26, 12],
       [19, 27, 30]])

In [93]:
a3 - b3

array([[ 1,  7, -1],
       [ 2,  6, -2],
       [-5, -3,  6]])

In [94]:
a3 * b3

array([[306, 144, 272],
       [ 35, 160,  35],
       [ 84, 180, 216]])

In [95]:
a3 / b3

array([[1.05882353, 1.77777778, 0.94117647],
       [1.4       , 1.6       , 0.71428571],
       [0.58333333, 0.8       , 1.5       ]])

###  Dimension ==>  Same
### Shape ==> Different

In [96]:
a1

array([10, 18, 17, 12, 11])

In [97]:
x1

array([13, 14, 12, 10, 11, 17, 10, 13])

In [98]:
a1 + x1

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [99]:
a1 + 6

array([16, 24, 23, 18, 17])

In [102]:
print(x2)
print("Shape : ",x2.shape)
print("Dimension : ",x2.ndim)

[[8 1 4]
 [6 7 8]
 [7 2 4]]
Shape :  (3, 3)
Dimension :  2


In [103]:
a2 + x2

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [104]:
y2 = np.random.randint(10,20,(3,1))

In [105]:
print( y2.shape)
print( y2.ndim)

(3, 1)
2


In [106]:
print("Shape : ",x2.shape)
print("Dimension : ",x2.ndim)

Shape :  (3, 3)
Dimension :  2


In [107]:
x2 + y2

array([[21, 14, 17],
       [16, 17, 18],
       [20, 15, 17]])

In [108]:
a2 + y2

ValueError: operands could not be broadcast together with shapes (2,2) (3,1) 

In [109]:
z2 = np.random.randint(10,20,(1,2))

In [110]:
z2.shape

(1, 2)

In [111]:
z2.ndim

2

In [112]:
a2.shape

(2, 2)

In [113]:
a2.ndim

2

In [114]:
z2 + a2

array([[23, 20],
       [22, 21]])

In [115]:
z2.shape

(1, 2)

In [116]:
y2.shape

(3, 1)

In [117]:
y2 + z2

array([[31, 30],
       [28, 27],
       [31, 30]])

In [118]:
x2

array([[8, 1, 4],
       [6, 7, 8],
       [7, 2, 4]])

In [119]:
x2.shape

(3, 3)

In [120]:
z2.shape

(1, 2)

In [121]:
x2 + z2

ValueError: operands could not be broadcast together with shapes (3,3) (1,2) 

In [122]:
a3 = np.random.randint(1,20,(2,3,4))

In [123]:
x3 = np.random.randint(1,20,(1,3,4))

In [124]:
a3.shape

(2, 3, 4)

In [125]:
x3.shape

(1, 3, 4)

In [126]:
a3 + x3

array([[[25, 11, 32, 17],
        [13, 12, 10, 24],
        [14, 24, 15, 10]],

       [[18, 14, 32, 19],
        [24, 26, 11, 18],
        [23, 28,  8, 17]]])

In [127]:
a3

array([[[18,  5, 16,  7],
        [ 8,  2,  5,  7],
        [ 8,  7,  8,  8]],

       [[11,  8, 16,  9],
        [19, 16,  6,  1],
        [17, 11,  1, 15]]])

In [128]:
a3.shape

(2, 3, 4)

In [130]:
a3.ndim

3

In [129]:
y2.shape

(3, 1)

In [131]:
y2.ndim

2

In [132]:
a3 + y2

array([[[31, 18, 29, 20],
        [18, 12, 15, 17],
        [21, 20, 21, 21]],

       [[24, 21, 29, 22],
        [29, 26, 16, 11],
        [30, 24, 14, 28]]])

In [133]:
a3.shape

(2, 3, 4)

In [134]:
a3.ndim

3

In [135]:
a2.shape

(2, 2)

In [136]:
a2.ndim

2

In [137]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,2) (2,3,4) 

In [138]:
np1 = np.random.randint(100,200,(3,2,5))

In [139]:
np1

array([[[186, 125, 170, 125, 101],
        [133, 185, 134, 181, 170]],

       [[105, 160, 192, 115, 102],
        [193, 122, 132, 169, 152]],

       [[158, 113, 173, 191, 152],
        [117, 101, 151, 153, 185]]])

In [140]:
np1.shape

(3, 2, 5)

In [141]:
np1.ndim

3

In [142]:
np2 = np.random.randint(100,200,(5,))

In [143]:
np2

array([118, 191, 169, 188, 153])

In [144]:
np2.shape

(5,)

In [145]:
np2.ndim

1

In [146]:
np1.shape

(3, 2, 5)

In [147]:
np2.shape

(5,)

In [148]:
np1 + np2

array([[[304, 316, 339, 313, 254],
        [251, 376, 303, 369, 323]],

       [[223, 351, 361, 303, 255],
        [311, 313, 301, 357, 305]],

       [[276, 304, 342, 379, 305],
        [235, 292, 320, 341, 338]]])