In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
ary1 = np.array([100,200,300,400,500])

In [4]:
ary1

array([100, 200, 300, 400, 500])

In [5]:
print(ary1)

[100 200 300 400 500]


In [6]:
type(ary1)

numpy.ndarray

In [10]:
ary1.shape  # Shape of Array

(5,)

In [8]:
ary1.size  # No of Element of Array

5

In [9]:
ary1.ndim  # Dimension

1

In [11]:
 ary1.dtype  # Datatype of values of array

dtype('int32')

In [13]:
ary1.itemsize # Size of value

4

###  2D Array using Array()

In [16]:
a2 = np.array([ [11,22,33, 10],[44,55,66,20],[77,88,99,30]  ])

In [17]:
a2

array([[11, 22, 33, 10],
       [44, 55, 66, 20],
       [77, 88, 99, 30]])

In [18]:
a2.shape

(3, 4)

In [19]:
a2.ndim

2

In [20]:
a2.size

12

In [21]:
a2.dtype

dtype('int32')

In [22]:
a2.itemsize

4

###  One's Function

In [24]:
ary_ones = np.ones((3,4))

In [25]:
ary_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
ary_ones.dtype

dtype('float64')

In [27]:
ary_ones.shape

(3, 4)

In [28]:
ary_ones.ndim

2

In [31]:
ary_3d = np.ones((2, 4, 6), dtype="int")

In [32]:
ary_3d

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [34]:
ary_3d.shape

(2, 4, 6)

In [35]:
ary_3d.ndim

3

In [36]:
ary_3d.size

48

In [38]:
ary_3d.dtype

dtype('int32')

In [41]:
ary_3d = ary_3d.astype("float")

In [42]:
ary_3d.dtype

dtype('float64')

###  Zeros Function

In [43]:
ary_zero = np.zeros((4,8))

In [44]:
ary_zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
ary_zero[1, 2] = 555

In [47]:
ary_zero

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 555.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

###  diagnal Array

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(5,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

###  Numerical Arrays

####  arange 

####  linspace

In [50]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [51]:
np.arange(1, 20, 2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [52]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [53]:
np.arange(10,20, -1)

array([], dtype=int32)

In [54]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
ar_ary = np.arange(1,1000, 2.5)

In [58]:
ar_ary

array([  1. ,   3.5,   6. ,   8.5,  11. ,  13.5,  16. ,  18.5,  21. ,
        23.5,  26. ,  28.5,  31. ,  33.5,  36. ,  38.5,  41. ,  43.5,
        46. ,  48.5,  51. ,  53.5,  56. ,  58.5,  61. ,  63.5,  66. ,
        68.5,  71. ,  73.5,  76. ,  78.5,  81. ,  83.5,  86. ,  88.5,
        91. ,  93.5,  96. ,  98.5, 101. , 103.5, 106. , 108.5, 111. ,
       113.5, 116. , 118.5, 121. , 123.5, 126. , 128.5, 131. , 133.5,
       136. , 138.5, 141. , 143.5, 146. , 148.5, 151. , 153.5, 156. ,
       158.5, 161. , 163.5, 166. , 168.5, 171. , 173.5, 176. , 178.5,
       181. , 183.5, 186. , 188.5, 191. , 193.5, 196. , 198.5, 201. ,
       203.5, 206. , 208.5, 211. , 213.5, 216. , 218.5, 221. , 223.5,
       226. , 228.5, 231. , 233.5, 236. , 238.5, 241. , 243.5, 246. ,
       248.5, 251. , 253.5, 256. , 258.5, 261. , 263.5, 266. , 268.5,
       271. , 273.5, 276. , 278.5, 281. , 283.5, 286. , 288.5, 291. ,
       293.5, 296. , 298.5, 301. , 303.5, 306. , 308.5, 311. , 313.5,
       316. , 318.5,

In [59]:
ar_ary.ndim

1

In [60]:
ar_ary.shape

(400,)

In [61]:
ar_ary.size

400

###  Linspace

In [62]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [64]:
lin_ary = np.linspace(1, 10, 20)

In [65]:
lin_ary.shape

(20,)

In [66]:
lin_ary.ndim

1

In [67]:
np.linspace(1, 10, endpoint=False)

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

In [68]:
np.linspace(1,10, retstep=True)

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
         2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
         4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
         6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
         8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]),
 0.1836734693877551)